export const ADD_TO_COUNTER = "ADD_TO_COUNTER"
export const DELETE_FROM_COUNTER = "DELETE_FROM_COUNTER"
export const GET_TOP_NUMBERS_LIST = "GET_TOP_NUMBERS_LIST"
export const GET_CANT_NUMBERS_LIST = "GET_CANT_NUMBERS_LIST"